#!/usr/bin/env bash

# sort order: ABab (vs. aAbB)
export LC_COLLATE='POSIX'

# Make vim the default editor
export EDITOR='vim'

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr
export PYTHONIOENCODING='UTF-8'

# Ignore <C-d> once; second time closes the terminal
export IGNOREEOF=1


# HISTORY settings -----------------------------------------------------------

# Better output
export HISTTIMEFORMAT='%h %d %H:%M  '

# Lines/commands stored
export HISTSIZE=100000 # in history list: in memory during session
export HISTFILESIZE="${HISTSIZE}" # in history file: on disk

# Do not store duplicates and commands that begin with a space
export HISTCONTROL='ignoreboth'

# Do not store these commands
export HISTIGNORE="&:[ ]*:history:h:ls:ll:la:l:clear"
