#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias -- -='cd -'  # escape dash with --

# Add verbose to all; prompt once for rm
alias mv='mv -v'

# ls shortcuts
alias l='ls -Gl'
alias l='ls --color=auto --group-directories-first'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -la'
alias ldot='ls -dl .??*' #list dot-files and dirs
alias llx='ls -lX' #sort by extention
alias llt='ls -lt' #sort by modification date

# Misc shortcuts
alias h=history
alias c=clear
alias cl='c;ll'
alias ipy=ipython
alias t="tree --noreport --dirsfirst -I 'node_modules|__pycache__'"
alias grep='grep -E --color=auto'
alias grepp="grep --include=*py"  # *py only

# virtualenv
alias deac='deactivate'

# be explicit about what python interpreter will run pip (use whatever is the current `python`)
alias pip="python -m pip"
