# .bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Enable color support for Mac
if [[ "$OSTYPE" == "darwin"* ]]; then
	eval $(gdircolors -b ~/.dircolors)
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Don't overwirte existing files by redirection
set -o noclobber 

export LC_COLLATE='POSIX'  # sort order: ABab (vs. aAbB)

export EDITOR='vim'  # default editor
export SYSTEMD_EDITOR='/usr/bin/vim'  # for systemctl edit

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr
export PYTHONIOENCODING='UTF-8'

export IGNOREEOF=1  # Ignore <C-d> once; next time close terminal

export HISTTIMEFORMAT='%h %d %H:%M  '
export HISTSIZE=-1  # Lines/commands stored in history list: in memory during session
export HISTFILESIZE="${HISTSIZE}"  # Lines/commands stored in history file: on disk
export HISTCONTROL='ignoreboth'  # Do not store duplicates and commands that begin with a space
export HISTIGNORE="&:[ ]*:history:h:ls:ll:la:l:clear"  # Do not store these commands
shopt -s histappend  # append to the history file, don't overwrite it


export ANSIBLE_NOCOWS=1  # because too many cows.


# Set terminal title to $PWD
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

# Load local .bashrc
if [[ -f ~/.bashrc-local ]]; then
	source ~/.bashrc-local
fi

# Load shell dotfiles
DOTFILES=dotfiles
source ~/${DOTFILES}/bash/aliases.sh
source ~/${DOTFILES}/bash/functions.sh

# Load git completions
#source ~/${DOTFILES}/git/git-completion.bash  # this doesn't seem to matter?

color_prompt=yes

# Basic prompt
PS1='${debian_chroot:+($debian_chroot)}\[\e[0;36m\]\u@\h$ \[\e[0m\]'

# display git branch
source ~/.git-prompt.sh
PS1='${debian_chroot:+($debian_chroot)}\[\e[0;36m\]\u@\h$(__git_ps1 "(%s)")\$ \[\e[0m\]'

# Uncomment include current directory
#PS1='${debian_chroot:+($debian_chroot)}\[\033[0;36m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

. "$HOME/.local/bin/env"  # Added by uv installer

# Ensure PATH is not extended w/duplicates on subsequent sourcing of .bashrc
if [ -z "$PATH_IS_SET" ]; then
	export PATH_IS_SET=1

	export PATH="$HOME/miniconda3/condabin:$PATH"

	# pyenv (do not use init - just use it to organize py versions)
	export PYENV_ROOT=$HOME/.pyenv
	export PATH="$PYENV_ROOT/bin:$PATH"

	# Install Ruby Gems to ~/gems
	export GEM_HOME="$HOME/gems"
	export PATH="$HOME/gems/bin:$PATH"
fi
