#!/usr/bin/env bash

# Load shell dotfiles
DOTFILES=dotfiles
source ~/${DOTFILES}/bash/aliases.sh
source ~/${DOTFILES}/bash/functions.sh

# Set terminal title to $PWD
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

# Don't overwirte existing files by redirection
set -o noclobber 

# Simple prompt: violet, host only
PS1="\[\e[1;35m\]\h$ \[\e[0m\]" 

# Load local .bashrc
if [[ -f ~/.bashrc-local ]]; then
	source ~/.bashrc-local
fi

# Load git completions
source ~/${DOTFILES}/git/git-completion.bash

# Load solarized colors for ls / gls for Mac
if [[ "$OSTYPE" != "darwin"* ]]; then
	eval $(dircolors ~/.dircolors)
else
	eval $(gdircolors -b ~/.dircolors)
fi

# pip bash completion
_pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F _pip_completion pip

# virtualenv/virtualenvwrapper:
if [[ -a /usr/local/bin/virtualenvwrapper.sh ]]; then
		export WORKON_HOME="${HOME}/.virtualenvs"
		export PROJECT_HOME="${HOME}/0dev/pythonvw_projects"
		source /usr/local/bin/virtualenvwrapper.sh
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# pyenv (do not use init - just use it to organize py versions)
export PYENV_ROOT=$HOME/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"

export LC_COLLATE='POSIX'  # sort order: ABab (vs. aAbB)

export EDITOR='vim'  # default editor

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr
export PYTHONIOENCODING='UTF-8'

export IGNOREEOF=1  # Ignore <C-d> once; next time close terminal

export ANSIBLE_NOCOWS=1  # because too many cows.


# HISTORY =======================================
export HISTTIMEFORMAT='%h %d %H:%M  '

# Lines/commands stored:
export HISTSIZE=9999  # in history list: in memory during session
export HISTFILESIZE="${HISTSIZE}" # in history file: on disk

# Do not store duplicates and commands that begin with a space
export HISTCONTROL='ignoreboth'

# Do not store these commands
export HISTIGNORE="&:[ ]*:history:h:ls:ll:la:l:clear"


# GALAXY ========================================
# main development repo
export GALAXYDEV=${DEVROOT}/galaxy/_galaxy/dev

# preloaded venvs named by their python versions
export GALAXYVENVS=${DEVROOT}/galaxy/_galaxy/dev-venvs

